# Generated by Django 5.1.3 on 2024-12-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crimes", "0002_areas_authgroup_authgrouppermissions_authpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locations",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="main",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="mocodes",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="crimelookup",
            table="crime_lookup",
        ),
    ]
